services:
  backend:
    build:
      context: '.'
      dockerfile: './docker/backend.dockerfile'
    volumes:
      - './config:/app/config:ro'
      - './tmp:/app/tmp'
      - './logs:/app/logs'
    ports:
      - '9002:80'

  queue_processor:
    build:
      context: '.'
      dockerfile: './docker/queueProcessor.dockerfile'
    volumes:
      - './config:/app/config:ro'
      - './tmp:/app/tmp'
      - './logs:/app/logs'
