services:
  backend:
    build:
      context: "."
      dockerfile: "./docker/backend.dockerfile"
    env_file: server/.env
    # entrypoint: ["npm", "run", "start:debug"]
    ports:
      - "9000:9000"

  frontend:
    build:
      context: "."
      dockerfile: "./docker/frontend.dockerfile"
      args:
        - API_BASE_URL=http://backend:9000
    environment:
      API_BASE_URL: http://backend:9000
      APP_PATH: ""
    ports:
      - "80:80"
